[package]
name = "zummi"
version = "0.1.1"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
description = "fun lib that produces spoonerisms"
license = "MIT OR Apache-2.0"

[[bin]]
test = false
doc = false
name = "zummi"
